### ISSUE TITLE
Intet virker, hverken public eller beta

### ISSUE THREAD

**Issue by wazerstar** [BenTearzz/MobilePayAlerts#5]
Jeg har prøvet med og uden itch.io app.

Med den nyeste version april 2019 giver den ikke nogen api nøgle i browser linjer og vil skrive invalid client_id

eksempel her for pb/mb

http://prntscr.com/ngydoe

Dette er linket den smider ind som ikke har nogen API i sig.
`https://www.pushbullet.com/authorize?client_id=pushbullet_client_id&redirect_uri=http://localhost:1337&response_type=code`

Streamlabs

http://prntscr.com/ngyeaf

Dette er linket den smider ind som ikke har nogen API i sig.

`https://www.streamlabs.com/api/v1.0/authorize?client_id=streamlabs_client_id&redirect_uri=http://localhost:1337&response_type=code&scope=donations.read+donations.create+alerts.write+alerts.create`

Den gamle version kan smider dog api nøgler afsted både til pb/mp og sl men den kan ikke finde ud af at genne api nøglerne i settings.ini, ergo der vil blive et konstant loop af man skal sætte MPA op ved hver opstart.

Jeg har både python 2 or python 3 med alle sub adds installeret og opdateret til det nyeste.

What to do?

**Comment by BenTearzz** [comment]
Hmm, kan ikke forstå hvorfor den gamle version ikke gemmer på Itch. Den burde kun spørge om opsætning hvis en af nøglerne mangler, så hvis både Streamlabs og Pushbullet ikke blev bekræftet første gang, så sker førstegangs opsætning igen.

Men kan dog godt se fejlen på den nyeste, det var noget jeg havde glemt at ændre før jeg compilede det til en .exe fil. (Har udgivet en ny version på Itch - **[MobilePayAlerts - Beta [April 2019]](https://tearzz.itch.io/mobilepayalerts))**

**Comment by wazerstar** [comment]
> 
> 
> Hmm, kan ikke forstå hvorfor den gamle version ikke gemmer på Itch. Den burde kun spørge om opsætning hvis en af nøglerne mangler, så hvis både Streamlabs og Pushbullet ikke blev bekræftet første gang, så sker førstegangs opsætning igen. (Det kan dog være at det er nogle tilladelser der er problemer med, måske gemmer den detaljerne hvis MPA bliver startet i administrator tilstand)
> 
> Men kan dog godt se fejlen på den nyeste, det var noget jeg havde glemt at ændre før jeg compilede det til en .exe fil. (Har udgivet en ny version på Itch - **[MobilePayAlerts - Beta [April 2019]](https://tearzz.itch.io/mobilepayalerts))**

Jeg har testet den nye, og den får smidt api nøgle afsted i browser og får gemt i settings filen nu.

Gendan knappe virker ikke og får programmet til at crashe, jeg har nu trykket start og prøvet at teste, men der sker intet.

pushbullet er åbnet måde på mobilen, browser og det er linket på streamlabs samt pushbullet med en fresh konto for sig selv, hvad gør jeg galt? har addet dig på steam hvis det er lidt nemmere :D

**Comment by BenTearzz** [comment]
492fd2ea6e428c2568cad8260963cd37300e0353

**Comment by wazerstar** [comment]
> 
> 
> [492fd2e](https://github.com/BenTearzz/MobilePayAlerts/commit/492fd2ea6e428c2568cad8260963cd37300e0353)

Lækkert jeg sidder klar til at teste når den er compilet :D

**Comment by BenTearzz** [comment]
Det er en kæmpe hjælp! Har lagt en ny opdatering ud på GitHub [dev](https://github.com/BenTearzz/MobilePayAlerts/tree/dev) grenen og på Itch (nu er der også et versionsnummer i beta titlen bare så det er nemmere at finde rundt i)

**Comment by wazerstar** [comment]
> 
> 
> Det er en kæmpe hjælp! Har lagt en ny opdatering ud på GitHub **[dev](https://github.com/BenTearzz/MobilePayAlerts/tree/dev)** grenen og på Itch (nu er der også et versionsnummer i beta titlen så det er nemmere at finde rundt i)

Du kan bare acceptere min steam friends, så går det meget hurtigere :D btw nu virker api nøgle ikke igen, variable bliver ikke smidt ind.

**Comment by wazerstar** [comment]
Hey var der kommet en nyere version jeg skulle teste :)

**Comment by BenTearzz** [comment]
Ikke endnu, jeg har haft virkelig travlt med afleveringer, imorgen har jeg ikke flere for i denne uge. Kan dog godt være at jeg har tid til det idag, skal lige finde ud af det.

**Comment by BenTearzz** [comment]
Jeg har nu lukket dette problem. Jeg fortsætter udviklingen på beta versionen, og prøver at finpudse den.
